### ISSUE TITLE
[New Feature] IP2Location LITE Database

### ISSUE THREAD

**Issue by m-cameron** [madisvain/geolocationapi#2]
Other than GeoIP2, you can also support free IP2Location LITE database for better accuracy.

https://lite.ip2location.com

**Comment by madisvain** [comment]
@m-cameron do you know it's better accuracy? I was initially planning on supporting only ip2location. I can certainly look into this yes.

**Comment by m-cameron** [comment]
@madisvain The accuracy is good.
