### ISSUE TITLE
Is it mandatory to self host it?

### ISSUE THREAD

**Issue by vishalvijay** [madisvain/geolocationapi#9]
Hi

This information is not available on the [website](https://ipgeolocationapi.com). So asking here.

Can we use https://api.ipgeolocationapi.com/geolocate/91.213.103.0 in production? (Mostly low traffic needs)

Is there any rate limit?

**Comment by madisvain** [comment]
@vishalvijay the API is free to use without self hosting. It can be self hosted if you want but it's not a requirement.

**Comment by vishalvijay** [comment]
@madisvain Thanks for the info.
